project:
  type: website

website:
  title: "PhD research project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Blogs.qmd
        text: Blog

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true
editor: visual

